# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 112090cd49f0f7e6877c0f1897c916c0e2af156fabe4ef4cf730429586a109d94e9ae71d60fb7f92872b60bba62a5daef3dc82b0e30cda805d09da5e6e1ed02f

test:
  secret_key_base: 8c894f12a6eeb045da7db1f5c78ccd9ca2e57edffd07a19d94c9831c723f57c0599a31144503621c78369af3ebca9c302f225a877c62748aac3341e45aee23c8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
